# Generated by Django 4.1.2 on 2022-10-31 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_profile_birth_date_remove_profile_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='frist_name',
            new_name='first_name',
        ),
    ]
